In [99]:
import tensorflow as tf
import keras
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Flatten,Dense

In [100]:
reviews=['nice food','amazing restaurant','too good','just loved it!','will go again',
         'horrible food','never go there','poor service','poor quality','needs improvement']
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [65]:
one_hot("amazing restaurant",30)

[23, 18]

In [66]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[20, 24], [23, 18], [13, 26], [17, 20, 25], [22, 9, 10], [17, 24], [13, 9, 18], [18, 25], [18, 29], [7, 26]]


In [101]:
arr=[]
for i in encoded_reviews:
    arr.append(len(i))
max_length=np.max(arr)

3


In [103]:
max_length = max_length
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[20 24  0]
 [23 18  0]
 [13 26  0]
 [17 20 25]
 [22  9 10]
 [17 24  0]
 [13  9 18]
 [18 25  0]
 [18 29  0]
 [ 7 26  0]]


In [109]:
embeded_vector_size=4
model = Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim= embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [110]:
x = padded_reviews
y = sentiment

In [111]:
model.build(input_shape=(None ,max_length))

In [112]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_19"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 3, 4)                │             120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_18 (Flatten)                 │ (None, 12)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 1)                   │              13 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 133 (532.00 B)

 Trainable params: 133 (532.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [113]:
model.fit(x,y,epochs=50,verbose=0)

In [114]:
model.evaluate(x,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 1.0000 - loss: 0.6463


[0.6462798714637756, 1.0]

In [116]:
weights=model.get_layer("embedding").get_weights()[0]

In [120]:
weights[11],weights[3]

(array([-0.04379735,  0.01170965,  0.03946998, -0.02397463], dtype=float32),
 array([-0.03549522, -0.0058761 ,  0.00199878, -0.04699736], dtype=float32))

here the dataset is small if you to find corelation use high dataset and try to implement this