In [106]:
import tensorflow as tf
import keras
import numpy as np
import os

In [54]:
#creating a dataframe
dff=[21,22,-108,31,-1,32,34,31]

In [55]:
tf_dataset=tf.data.Dataset.from_tensor_slices(dff)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [56]:
for i in tf_dataset:
  print(i.numpy())

21
22
-108
31
-1
32
34
31


In [57]:
for i in tf_dataset.take(3):
  print(i.numpy())

21
22
-108


In [58]:
df=tf_dataset.filter(lambda x:x>0)
for i in df:
  print(i.numpy())

21
22
31
32
34
31


In [59]:
df=df.map(lambda x: x*72)
for i in df:
  print(i.numpy())

1512
1584
2232
2304
2448
2232


In [60]:
df=df.shuffle(2)
for i in df.as_numpy_iterator():
  print(i)

1584
2232
2304
1512
2448
2232


In [61]:
for i in df.batch(3):
  print(i.numpy())

[1584 2232 2304]
[2448 1512 2232]


In [62]:
tf_dataset=tf.data.Dataset.from_tensor_slices(dff)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [63]:
tf_dataset=tf_dataset.filter(lambda x: x>0).map(lambda x: x*72).shuffle(2).batch(2)

In [64]:
for i in tf_dataset.as_numpy_iterator():
  print(i)

[1512 1584]
[2304 2232]
[2448 2232]


In [75]:
image=tf.data.Dataset.list_files("/content/dog/*",shuffle=False)

In [76]:
for i in image.take(3):
  print(i.numpy())

b'/content/dog/pexels-bertellifotografia-1906153.jpg'
b'/content/dog/pexels-chevanon-1108099.jpg'
b'/content/dog/pexels-chevonrossouw-2558605.jpg'


In [77]:
image=image.shuffle(200)
for i in image.take(3):
  print(i.numpy())

b'/content/dog/pexels-chevanon-1108099.jpg'
b'/content/dog/pexels-tranmautritam-2061057.jpg'
b'/content/dog/pexels-bertellifotografia-1906153.jpg'


In [78]:
label=["cat","dog"]

In [99]:
img_count=len(image) # i dont know why i face this error need to  check
img_count

TypeError: 'int' object is not callable

In [86]:
le=int(img_count*.8)
train=image.take(le)
test=image.skip(le)

In [108]:
def get_label(path):
  return tf.strings.split(path,os.path.sep)[-2]

In [121]:
def get(path):
  label=get_label(path)
  img = tf.io.read_file(path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img,[128,128])
  return img,label

In [127]:
train=train.map(get)
for img,label in train.take(3):
  print(img)
  print(label)

tf.Tensor(
[[[ 72.21094    56.210938   30.210938 ]
  [ 99.         78.         49.       ]
  [103.         82.         53.       ]
  ...
  [ 21.027344   17.027344    6.0273438]
  [ 23.570312   16.570312    6.5703125]
  [ 22.964844   15.964844    5.9648438]]

 [[ 80.31641    63.316406   35.316406 ]
  [102.         81.         50.367188 ]
  [103.97266    79.97266    51.972656 ]
  ...
  [ 22.710938   15.7109375   5.7109375]
  [ 22.         15.          5.       ]
  [ 23.605469   16.605469    6.6054688]]

 [[ 95.60547    74.60547    45.60547  ]
  [102.         82.         49.       ]
  [101.         77.         51.       ]
  ...
  [ 24.445312   18.445312    6.4453125]
  [ 22.367188   15.3671875   5.3671875]
  [ 19.         15.          6.       ]]

 ...

 [[ 83.         69.14844    39.703125 ]
  [ 39.027252   31.027252   18.027252 ]
  [ 17.         14.          5.       ]
  ...
  [ 25.023285   19.023285    7.023285 ]
  [ 25.972748   19.972748    7.972748 ]
  [ 28.605469   22.605469   10.60

In [128]:
def scale(image,label):
  return image/255,label

In [131]:
train=train.map(scale)
for img,label in train.take(3):
  print(img)
  print(label)

tf.Tensor(
[[[0.00030571 0.00063239 0.00039985]
  [0.00036236 0.00057766 0.00037774]
  [0.00026144 0.00047674 0.00027682]
  ...
  [0.0013563  0.00117176 0.00095645]
  [0.00132415 0.00123188 0.00101658]
  [0.00146184 0.00135419 0.00110813]]

 [[0.00035371 0.00056901 0.00036909]
  [0.00032295 0.00053825 0.00033833]
  [0.0002922  0.00053825 0.00033833]
  ...
  [0.00135152 0.00113322 0.00084102]
  [0.00121924 0.00114235 0.00083477]
  [0.0013003  0.00122341 0.00091583]]

 [[0.00047058 0.00080891 0.0004552 ]
  [0.00046902 0.00085348 0.00051515]
  [0.00041767 0.00069448 0.00044842]
  ...
  [0.00123636 0.00114409 0.00080576]
  [0.00129701 0.00112785 0.00082027]
  [0.00122366 0.00113139 0.00079306]]

 ...

 [[0.00079161 0.00100691 0.00049942]
  [0.00070222 0.00094828 0.0005023 ]
  [0.00061527 0.00092284 0.00049224]
  ...
  [0.00055363 0.00112265 0.00049212]
  [0.00057421 0.00111247 0.00049732]
  [0.00055363 0.00109189 0.00047674]]

 [[0.00075154 0.00107449 0.00047472]
  [0.00072712 0.00106545 0

New text pipeline creation


In [158]:
reviews_ds=tf.data.Dataset.list_files("/content/comments/*/*",shuffle=False)

In [159]:
for i in reviews_ds:
  print(i.numpy())

b'/content/comments/Negative/neg_1.txt'
b'/content/comments/Negative/neg_2.txt'
b'/content/comments/Positive/pos_1.txt'
b'/content/comments/Positive/pos_2.txt'


In [160]:
def extract_review(path):
  return tf.io.read_file(path),tf.strings.split(path,os.path.sep)[-2]

In [161]:
reviews_ds_1 = reviews_ds.map(extract_review)
for review, label in reviews_ds_1:
    print("Review: ",review.numpy()[:])
    print("Label: ",label.numpy())

Review:  b"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.\n"
Label:  b'Negative'
Review:  b"This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, a

In [162]:
reviews_ds_2 = reviews_ds_1.filter(lambda review, label: review!="")
for review, label in reviews_ds_2.as_numpy_iterator():
    print("Review: ",review[:])
    print("Label: ",label)

Review:  b"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.\n"
Label:  b'Negative'
Review:  b"This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, a

In [163]:
final_ds = reviews_ds.map(extract_review).filter(lambda review, label: review!="").shuffle(3)
for review, label in final_ds.as_numpy_iterator():
    print("Review:",review[:])
    print("Label:",label)

Review: b"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due 